apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/kirtiazad11111/spring-petclinic:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/kirtiazad11111/spring-petclinic:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-petclinic
        chartPath: charts/spring-petclinic
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/kirtiazad11111/spring-petclinic"
          image.tag: "{{.DIGEST_HEX}}"
